CREATE TABLE `componentCalculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportId` int NOT NULL,
	`inspectionId` int NOT NULL,
	`componentName` varchar(128),
	`componentType` varchar(64),
	`parentComponentId` int,
	`componentPath` varchar(255),
	`hierarchyLevel` int DEFAULT 0,
	`designPressure` int,
	`designTemperature` int,
	`insideDiameter` varchar(32),
	`materialSpec` varchar(128),
	`allowableStress` int,
	`jointEfficiency` varchar(10),
	`nominalThickness` varchar(16),
	`previousThickness` varchar(16),
	`actualThickness` varchar(16),
	`minimumThickness` varchar(16),
	`calculatedMAWP` int,
	`designMAWP` int,
	`corrosionRate` varchar(16),
	`corrosionRateLT` varchar(16),
	`corrosionRateST` varchar(16),
	`governingRate` varchar(16),
	`governingRateReason` varchar(255),
	`remainingLife` varchar(16),
	`nextInspectionYears` varchar(16),
	`nextInspectionDate` timestamp,
	`timeSpan` varchar(16),
	`pdfOriginalActualThickness` varchar(16),
	`pdfOriginalMinThickness` varchar(16),
	`pdfOriginalMAWP` varchar(16),
	`pdfOriginalCorrosionRate` varchar(16),
	`pdfOriginalRemainingLife` varchar(16),
	`isBelowMinimum` boolean DEFAULT false,
	`statusMessage` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `componentCalculations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `externalInspections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`foundationCondition` varchar(64),
	`foundationNotes` text,
	`shellCondition` varchar(64),
	`shellNotes` text,
	`headsCondition` varchar(64),
	`headsNotes` text,
	`nozzlesCondition` varchar(64),
	`nozzlesNotes` text,
	`insulationCondition` varchar(64),
	`insulationNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `externalInspections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `importedFiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`filename` varchar(255),
	`originalFilename` varchar(255),
	`fileType` varchar(32),
	`fileUrl` varchar(512),
	`fileKey` varchar(255),
	`parserUsed` varchar(32),
	`parseStatus` varchar(32) DEFAULT 'pending',
	`parseResult` text,
	`status` varchar(32) DEFAULT 'pending',
	`fieldsExtracted` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `importedFiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inspectionFindings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`reportId` int,
	`findingNumber` int,
	`category` varchar(64),
	`severity` enum('critical','major','minor','observation') DEFAULT 'observation',
	`description` text,
	`location` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inspectionFindings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inspections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`vesselTagNumber` varchar(64),
	`vesselName` varchar(255),
	`manufacturer` varchar(255),
	`serialNumber` varchar(128),
	`yearBuilt` varchar(10),
	`nationalBoardNumber` varchar(64),
	`designPressure` int,
	`designTemperature` int,
	`mawp` int,
	`mdmt` int,
	`operatingPressure` int,
	`operatingTemperature` int,
	`materialSpec` varchar(128),
	`allowableStress` int,
	`jointEfficiency` varchar(10),
	`radiographyType` varchar(10),
	`insideDiameter` varchar(32),
	`shellLength` varchar(32),
	`nominalThickness` varchar(32),
	`corrosionAllowance` varchar(32),
	`vesselOrientation` varchar(32),
	`headType` varchar(64),
	`constructionCode` varchar(64),
	`vesselConfiguration` varchar(64),
	`insulationType` varchar(64),
	`productService` varchar(128),
	`specificGravity` varchar(16),
	`inspectionDate` timestamp,
	`previousInspectionDate` timestamp,
	`nextInspectionDate` timestamp,
	`inspectorName` varchar(128),
	`clientName` varchar(255),
	`reportNumber` varchar(64),
	`status` enum('draft','in_progress','completed','archived') NOT NULL DEFAULT 'draft',
	`previousInspectionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inspections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `internalInspections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`shellCondition` varchar(64),
	`shellNotes` text,
	`headsCondition` varchar(64),
	`headsNotes` text,
	`internalsCondition` varchar(64),
	`internalsNotes` text,
	`weldCondition` varchar(64),
	`weldNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `internalInspections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `materialStressValues` (
	`id` int AUTO_INCREMENT NOT NULL,
	`materialSpec` varchar(128) NOT NULL,
	`materialCategory` varchar(64),
	`description` text,
	`temperature` int NOT NULL,
	`allowableStress` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `materialStressValues_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nozzleEvaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`nozzleId` varchar(64),
	`cmlNumber` varchar(32),
	`serviceType` varchar(64),
	`size` varchar(16),
	`schedule` varchar(16),
	`materialSpec` varchar(128),
	`nominalThickness` varchar(16),
	`previousThickness` varchar(16),
	`actualThickness` varchar(16),
	`minimumThickness` varchar(16),
	`corrosionAllowance` varchar(16),
	`corrosionRate` varchar(16),
	`remainingLife` varchar(16),
	`age` varchar(16),
	`status` varchar(32) DEFAULT 'acceptable',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nozzleEvaluations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `photos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`filename` varchar(255),
	`url` varchar(512),
	`fileKey` varchar(255),
	`category` varchar(64),
	`caption` text,
	`annotations` text,
	`sequence` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `photos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `professionalReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`userId` int NOT NULL,
	`reportNumber` varchar(64),
	`reportDate` timestamp,
	`executiveSummary` text,
	`inspectionScope` text,
	`inspectionResults` text,
	`pdfUrl` varchar(512),
	`filename` varchar(255),
	`fileKey` varchar(512),
	`url` varchar(512),
	`status` enum('draft','generated','approved','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `professionalReports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`reportId` int,
	`recommendationNumber` int,
	`priority` enum('immediate','high','medium','low') DEFAULT 'medium',
	`description` text,
	`dueDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tmlReadings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspectionId` int NOT NULL,
	`cmlNumber` varchar(32),
	`tmlId` varchar(64),
	`location` varchar(255),
	`componentType` varchar(64),
	`readingType` varchar(32),
	`nozzleSize` varchar(16),
	`angle` varchar(16),
	`tml1` varchar(16),
	`tml2` varchar(16),
	`tml3` varchar(16),
	`tml4` varchar(16),
	`nominalThickness` varchar(16),
	`previousThickness` varchar(16),
	`actualThickness` varchar(16),
	`minimumThickness` varchar(16),
	`isAnomaly` boolean DEFAULT false,
	`anomalyReason` varchar(255),
	`excludeFromCalculation` boolean DEFAULT false,
	`status` varchar(32) DEFAULT 'good',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tmlReadings_id` PRIMARY KEY(`id`)
);
